/* R_init_nlmrs_extendr is generated by the extendr macro in lib.rs.
   R looks for R_init_<package> on dlopen; we bridge to the generated symbol. */
void R_init_nlmrs_extendr(void *dll);

void R_init_nlmrs(void *dll) {
    R_init_nlmrs_extendr(dll);
}
