# Generated by extendr — do not edit by hand.
#
# These thin .Call stubs mirror every Rust function exported via #[extendr].
# The symbol names (wrap__r_*) are produced by the extendr macro in lib.rs.
# Normally auto-generated by rextendr::document(); included manually so the
# package installs without needing rextendr at build time.

r_random <- function(rows, cols, seed = NULL) {
  .Call(wrap__r_random, rows, cols, seed)
}

r_random_element <- function(rows, cols, n = 50000, seed = NULL) {
  .Call(wrap__r_random_element, rows, cols, n, seed)
}

r_planar_gradient <- function(rows, cols, direction = NULL, seed = NULL) {
  .Call(wrap__r_planar_gradient, rows, cols, direction, seed)
}

r_edge_gradient <- function(rows, cols, direction = NULL, seed = NULL) {
  .Call(wrap__r_edge_gradient, rows, cols, direction, seed)
}

r_distance_gradient <- function(rows, cols, seed = NULL) {
  .Call(wrap__r_distance_gradient, rows, cols, seed)
}

r_wave_gradient <- function(rows, cols, period = 2.5, direction = NULL, seed = NULL) {
  .Call(wrap__r_wave_gradient, rows, cols, period, direction, seed)
}

r_midpoint_displacement <- function(rows, cols, h = 1.0, seed = NULL) {
  .Call(wrap__r_midpoint_displacement, rows, cols, h, seed)
}

r_hill_grow <- function(rows, cols, n = 10000L, runaway = TRUE,
                        kernel = NULL, only_grow = FALSE, seed = NULL) {
  .Call(wrap__r_hill_grow, rows, cols, n, runaway, kernel, only_grow, seed)
}

r_perlin_noise <- function(rows, cols, scale_factor = 4.0, seed = NULL) {
  .Call(wrap__r_perlin_noise, rows, cols, scale_factor, seed)
}

r_fbm_noise <- function(rows, cols, scale_factor = 4.0, octaves = 6L,
                        persistence = 0.5, lacunarity = 2.0, seed = NULL) {
  .Call(wrap__r_fbm_noise, rows, cols, scale_factor, octaves,
        persistence, lacunarity, seed)
}
